name: Deploy to EC2 machine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: #user defined
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v4

      - name: Copy code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSHKEY }}
          port: 22
          source: ./
          target: /home/ubuntu