name: Deploy to EC2 machine

on:
  push:
    branches:
      - main
  pull_request:
    branches: -main

jobs:
  build: #user defined
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v4